/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F269_6232();
extern void F271_6394();
extern void F269_6236();
extern void F272_6398();
extern void F274_6562();
extern void F272_6403();
extern void F335_4079();
extern void F298_6078();
extern void F138_1650();
extern EIF_REFERENCE F138_1637();
extern EIF_BOOLEAN F138_1649();
extern EIF_BOOLEAN F138_1657();
extern void F138_1659();
extern void F138_1660();
extern void F138_1661();
extern void F79_1308();
extern EIF_TYPED_VALUE F79_1309();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F269_6232;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F269_6236;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F272_6398;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F272_6403;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F335_4079;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F271_6394;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F274_6562;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F298_6078;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F138_1650;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F138_1649;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F138_1637;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F138_1657;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F138_1659;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F138_1660;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F138_1661;

	egc_str_dtype = 270;

	egc_immstr8_dtype = 269;

	egc_str32_dtype = 273;

	egc_immstr32_dtype = 272;
	egc_arr_dtype = 334;
	egc_tup_dtype = 222;
	egc_disp_rout_id = 2383;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x024D;
	egc_sp_wchar = 0x022F;
	egc_sp_bool = 0x03A0;
	egc_sp_uint8 = 0x0262;
	egc_sp_uint16 = 0x037C;
	egc_sp_uint32 = 0x018E;
	egc_sp_uint64 = 0x01D9;
	egc_sp_int8 = 0x0334;
	egc_sp_int16 = 0x0310;
	egc_sp_int32 = 0x01C9;
	egc_sp_int64 = 0x0358;
	egc_sp_real32 = 0x02EC;
	egc_sp_real64 = 0x02D8;
	egc_sp_pointer = 0x0217;
	egc_sp_ref = 0x0155;

	egc_uint8_dtype = 245;
	egc_uint16_dtype = 242;
	egc_uint32_dtype = 239;
	egc_uint64_dtype = 236;
	egc_int8_dtype = 233;
	egc_int16_dtype = 230;
	egc_int32_dtype = 227;
	egc_int64_dtype = 224;
	egc_bool_dtype = 260;
	egc_real32_dtype = 248;
	egc_char_dtype = 257;
	egc_wchar_dtype = 254;
	egc_real64_dtype = 251;
	egc_point_dtype = 263;

	egc_exception_dtype = 97;
	egc_except_emnger_dtype = 137;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_calculus";
	egc_system_location = "D:\\prod\\simple_calculus\\EIFGENs\\simple_calculus_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1769708015;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1016;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "TEST_APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 832;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2954;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5309;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 78;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F79_1308;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F79_1309;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 38; /* TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 193; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 291; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
